### ISSUE TITLE
pyramid_heroku.structlog setting should not be needed

### ISSUE THREAD

**Issue by zupo** [niteoweb/pyramid_heroku#3]
Structlog detection should be automatic.

Also see https://github.com/niteoweb/ebn/pull/2189#pullrequestreview-54133542.

**Comment by enkidulan** [comment]
cannot assign on myself, but I'm on it

**Comment by enkidulan** [comment]
Making `pyramid_heroku` to use `structlog` should be explicit. Guessing which one to use `logging` or `structlog` is unreliable and error prone. All configuration should be explicit. 

@zupo, If you insist I can check if `structlog` is installed and use it for logging in that case.
  
Besides that, `logging` and `structlog` have different interfaces, they are not interchangeable, and I see no any good way to solve this. It will be more beneficial to use only one way for logging. 

The good solution may be to add `structlog` to package `install_requires` and use it all the time. I'll create PR for this one. 

In case if this package is going to be a public one and released on PyPI, it may be better to go with build-in `logging` module.

**Comment by cas--** [comment]
@enkidulan I saw this in docs: http://docs.niteoweb.com/pyramid_bimt/conventions.html#structlog-overview

**Comment by zupo** [comment]
@dz0ny care to chip in please?

**Comment by enkidulan** [comment]
@zupo @dz0ny I've created PR with switching on using only `structlog` - https://github.com/niteoweb/pyramid_heroku/pull/4 . But I would rather leave the code as it is or make it use only build-in `logging` module.

**Comment by enkidulan** [comment]
@zupo @dz0ny code as it now seems as a perfect solution to me.Tomorrow I will close this issue and PR as not needed if I don't get any response from you.

**Comment by enkidulan** [comment]
During the discussion with zupo dz0ny we decided to close this issue and leave the code as it is.
